# Generated by Django 5.0.2 on 2024-09-25 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitems',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='orderitems',
            old_name='order_id',
            new_name='order',
        ),
    ]
