# Generated by Django 5.0.2 on 2024-09-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServicesApp', '0002_rename_content_service_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='updatedAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
